apiVersion: v1
kind: Service
metadata:
  name: nginx-1
  labels:
    app: nginx-1
spec:
  type: NodePort
  selector:
    app: nginx-1
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-2
  labels:
    app: nginx-2
spec:
  type: NodePort
  selector:
    app: nginx-2
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80